pipeline {
    agent {
        label 'devops'
    }
    options {
        timestamps()
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn386 -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn386 test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
